###
# This is the place to override the deploy cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "deploy/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the deploy user and shell:
#
#normal[:opsworks][:deploy_user][:shell] = '/bin/zsh'
#normal[:opsworks][:deploy_user][:user] = 'deploy'

normal[:opsworks][:rails][:ignore_bundler_groups] = ['test', 'development', 'edi']

normal[:deploy][application][:environment] = {"RAILS_ENV" => deploy[:rails_env],
                                              "RUBYOPT" => "",
                                              "NOKOGIRI_USE_SYSTEM_LIBRARIES" => "1",
                                              "RACK_ENV" => deploy[:rails_env],
                                              "HOME" => node[:deploy][application][:home]}
